spring:
  datasource:
    url: jdbc:hsqldb:hsql://microservicios-hsqldb3
    username: sa
    password: 
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
  jpa:
    database-platform: org.hibernate.dialect.HSQLDialect
    hibernate:
      ddl-auto: create
      
logging:
  level:
    org:
      hibernate:
        SQL: debug
